# Generated by Django 3.1.14 on 2023-08-07 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0007_auto_20230807_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='evolved_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evolutions', to='pokemon_entities.pokemon', verbose_name='Из кого эволюционировал'),
        ),
    ]
