# Generated by Django 3.1.14 on 2023-08-21 00:19

from django.db import migrations, models


def delete_entities_with_null_dates(apps, schema_editor):
    PokemonEntity = apps.get_model('pokemon_entities', 'PokemonEntity')
    entities_to_delete = PokemonEntity.objects.filter(appeared_at__isnull=True) | PokemonEntity.objects.filter(
        disappeared_at__isnull=True)
    entities_to_delete.delete()

class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0012_auto_20230820_2358'),
    ]

    operations = [
        migrations.RunPython(delete_entities_with_null_dates, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='pokemonentity',
            name='appeared_at',
            field=models.DateTimeField(verbose_name="Время появления на карте"),
        ),
        migrations.AlterField(
            model_name='pokemonentity',
            name='disappeared_at',
            field=models.DateTimeField(verbose_name="Время исчезновения с карты"),
        ),
    ]
